//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AdjustedPrice = newAdjustedPriceTable("public", "adjusted_price", "")

type adjustedPriceTable struct {
	postgres.Table

	//Columns
	ID        postgres.ColumnInteger
	Date      postgres.ColumnDate
	Symbol    postgres.ColumnString
	Price     postgres.ColumnFloat
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AdjustedPriceTable struct {
	adjustedPriceTable

	EXCLUDED adjustedPriceTable
}

// AS creates new AdjustedPriceTable with assigned alias
func (a AdjustedPriceTable) AS(alias string) *AdjustedPriceTable {
	return newAdjustedPriceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AdjustedPriceTable with assigned schema name
func (a AdjustedPriceTable) FromSchema(schemaName string) *AdjustedPriceTable {
	return newAdjustedPriceTable(schemaName, a.TableName(), a.Alias())
}

func newAdjustedPriceTable(schemaName, tableName, alias string) *AdjustedPriceTable {
	return &AdjustedPriceTable{
		adjustedPriceTable: newAdjustedPriceTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAdjustedPriceTableImpl("", "excluded", ""),
	}
}

func newAdjustedPriceTableImpl(schemaName, tableName, alias string) adjustedPriceTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		DateColumn      = postgres.DateColumn("date")
		SymbolColumn    = postgres.StringColumn("symbol")
		PriceColumn     = postgres.FloatColumn("price")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, DateColumn, SymbolColumn, PriceColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{DateColumn, SymbolColumn, PriceColumn, CreatedAtColumn}
	)

	return adjustedPriceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Date:      DateColumn,
		Symbol:    SymbolColumn,
		Price:     PriceColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
