//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AppUserProfile = newAppUserProfileTable("public", "app_user_profile", "")

type appUserProfileTable struct {
	postgres.Table

	// Columns
	AuthUserID  postgres.ColumnString
	Email       postgres.ColumnString
	DisplayName postgres.ColumnString
	PhoneNumber postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AppUserProfileTable struct {
	appUserProfileTable

	EXCLUDED appUserProfileTable
}

// AS creates new AppUserProfileTable with assigned alias
func (a AppUserProfileTable) AS(alias string) *AppUserProfileTable {
	return newAppUserProfileTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AppUserProfileTable with assigned schema name
func (a AppUserProfileTable) FromSchema(schemaName string) *AppUserProfileTable {
	return newAppUserProfileTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AppUserProfileTable with assigned table prefix
func (a AppUserProfileTable) WithPrefix(prefix string) *AppUserProfileTable {
	return newAppUserProfileTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AppUserProfileTable with assigned table suffix
func (a AppUserProfileTable) WithSuffix(suffix string) *AppUserProfileTable {
	return newAppUserProfileTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAppUserProfileTable(schemaName, tableName, alias string) *AppUserProfileTable {
	return &AppUserProfileTable{
		appUserProfileTable: newAppUserProfileTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newAppUserProfileTableImpl("", "excluded", ""),
	}
}

func newAppUserProfileTableImpl(schemaName, tableName, alias string) appUserProfileTable {
	var (
		AuthUserIDColumn  = postgres.StringColumn("auth_user_id")
		EmailColumn       = postgres.StringColumn("email")
		DisplayNameColumn = postgres.StringColumn("display_name")
		PhoneNumberColumn = postgres.StringColumn("phone_number")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{AuthUserIDColumn, EmailColumn, DisplayNameColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{EmailColumn, DisplayNameColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return appUserProfileTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AuthUserID:  AuthUserIDColumn,
		Email:       EmailColumn,
		DisplayName: DisplayNameColumn,
		PhoneNumber: PhoneNumberColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
