//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BacktestJob = newBacktestJobTable("public", "backtest_job", "")

type backtestJobTable struct {
	postgres.Table

	//Columns
	BacktestJobID    postgres.ColumnString
	StrategyID       postgres.ColumnString
	Status           postgres.ColumnString
	CurrentStage     postgres.ColumnString
	ProgressPct      postgres.ColumnInteger
	Result           postgres.ColumnString
	ErrorMessage     postgres.ColumnString
	CreatedAt        postgres.ColumnTimestampz
	UpdatedAt        postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type BacktestJobTable struct {
	backtestJobTable

	EXCLUDED backtestJobTable
}

// AS creates new BacktestJobTable with assigned alias
func (a BacktestJobTable) AS(alias string) *BacktestJobTable {
	return newBacktestJobTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BacktestJobTable with assigned schema name
func (a BacktestJobTable) FromSchema(schemaName string) *BacktestJobTable {
	return newBacktestJobTable(schemaName, a.TableName(), a.Alias())
}

func newBacktestJobTable(schemaName, tableName, alias string) *BacktestJobTable {
	return &BacktestJobTable{
		backtestJobTable: newBacktestJobTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newBacktestJobTableImpl("", "excluded", ""),
	}
}

func newBacktestJobTableImpl(schemaName, tableName, alias string) backtestJobTable {
	var (
		BacktestJobIDColumn    = postgres.StringColumn("backtest_job_id")
		StrategyIDColumn      = postgres.StringColumn("strategy_id")
		StatusColumn          = postgres.StringColumn("status")
		CurrentStageColumn    = postgres.StringColumn("current_stage")
		ProgressPctColumn     = postgres.IntegerColumn("progress_pct")
		ResultColumn          = postgres.StringColumn("result")
		ErrorMessageColumn    = postgres.StringColumn("error_message")
		CreatedAtColumn       = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampzColumn("updated_at")
		allColumns            = postgres.ColumnList{BacktestJobIDColumn, StrategyIDColumn, StatusColumn, CurrentStageColumn, ProgressPctColumn, ResultColumn, ErrorMessageColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{BacktestJobIDColumn, StrategyIDColumn, StatusColumn, CurrentStageColumn, ProgressPctColumn, ResultColumn, ErrorMessageColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return backtestJobTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		BacktestJobID:    BacktestJobIDColumn,
		StrategyID:      StrategyIDColumn,
		Status:          StatusColumn,
		CurrentStage:    CurrentStageColumn,
		ProgressPct:     ProgressPctColumn,
		Result:          ResultColumn,
		ErrorMessage:    ErrorMessageColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
