//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmailPreference = newEmailPreferenceTable("public", "email_preference", "")

type emailPreferenceTable struct {
	postgres.Table

	//Columns
	EmailPreferenceID postgres.ColumnString
	UserAccountID     postgres.ColumnString
	EmailType         postgres.ColumnString
	Frequency         postgres.ColumnString
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type EmailPreferenceTable struct {
	emailPreferenceTable

	EXCLUDED emailPreferenceTable
}

// AS creates new EmailPreferenceTable with assigned alias
func (a EmailPreferenceTable) AS(alias string) *EmailPreferenceTable {
	return newEmailPreferenceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmailPreferenceTable with assigned schema name
func (a EmailPreferenceTable) FromSchema(schemaName string) *EmailPreferenceTable {
	return newEmailPreferenceTable(schemaName, a.TableName(), a.Alias())
}

func newEmailPreferenceTable(schemaName, tableName, alias string) *EmailPreferenceTable {
	return &EmailPreferenceTable{
		emailPreferenceTable: newEmailPreferenceTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newEmailPreferenceTableImpl("", "excluded", ""),
	}
}

func newEmailPreferenceTableImpl(schemaName, tableName, alias string) emailPreferenceTable {
	var (
		EmailPreferenceIDColumn = postgres.StringColumn("email_preference_id")
		UserAccountIDColumn     = postgres.StringColumn("user_account_id")
		EmailTypeColumn         = postgres.StringColumn("email_type")
		FrequencyColumn         = postgres.StringColumn("frequency")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		allColumns              = postgres.ColumnList{EmailPreferenceIDColumn, UserAccountIDColumn, EmailTypeColumn, FrequencyColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{UserAccountIDColumn, EmailTypeColumn, FrequencyColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return emailPreferenceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		EmailPreferenceID: EmailPreferenceIDColumn,
		UserAccountID:     UserAccountIDColumn,
		EmailType:         EmailTypeColumn,
		Frequency:         FrequencyColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
