//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ExcessTradeVolume = newExcessTradeVolumeTable("public", "excess_trade_volume", "")

type excessTradeVolumeTable struct {
	postgres.Table

	// Columns
	ExcessTradeVolumeID postgres.ColumnString
	TickerID            postgres.ColumnString
	Quantity            postgres.ColumnFloat
	TradeOrderID        postgres.ColumnString
	CreatedAt           postgres.ColumnTimestampz
	RebalancerRunID     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ExcessTradeVolumeTable struct {
	excessTradeVolumeTable

	EXCLUDED excessTradeVolumeTable
}

// AS creates new ExcessTradeVolumeTable with assigned alias
func (a ExcessTradeVolumeTable) AS(alias string) *ExcessTradeVolumeTable {
	return newExcessTradeVolumeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ExcessTradeVolumeTable with assigned schema name
func (a ExcessTradeVolumeTable) FromSchema(schemaName string) *ExcessTradeVolumeTable {
	return newExcessTradeVolumeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ExcessTradeVolumeTable with assigned table prefix
func (a ExcessTradeVolumeTable) WithPrefix(prefix string) *ExcessTradeVolumeTable {
	return newExcessTradeVolumeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ExcessTradeVolumeTable with assigned table suffix
func (a ExcessTradeVolumeTable) WithSuffix(suffix string) *ExcessTradeVolumeTable {
	return newExcessTradeVolumeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newExcessTradeVolumeTable(schemaName, tableName, alias string) *ExcessTradeVolumeTable {
	return &ExcessTradeVolumeTable{
		excessTradeVolumeTable: newExcessTradeVolumeTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newExcessTradeVolumeTableImpl("", "excluded", ""),
	}
}

func newExcessTradeVolumeTableImpl(schemaName, tableName, alias string) excessTradeVolumeTable {
	var (
		ExcessTradeVolumeIDColumn = postgres.StringColumn("excess_trade_volume_id")
		TickerIDColumn            = postgres.StringColumn("ticker_id")
		QuantityColumn            = postgres.FloatColumn("quantity")
		TradeOrderIDColumn        = postgres.StringColumn("trade_order_id")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		RebalancerRunIDColumn     = postgres.StringColumn("rebalancer_run_id")
		allColumns                = postgres.ColumnList{ExcessTradeVolumeIDColumn, TickerIDColumn, QuantityColumn, TradeOrderIDColumn, CreatedAtColumn, RebalancerRunIDColumn}
		mutableColumns            = postgres.ColumnList{TickerIDColumn, QuantityColumn, TradeOrderIDColumn, CreatedAtColumn, RebalancerRunIDColumn}
	)

	return excessTradeVolumeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ExcessTradeVolumeID: ExcessTradeVolumeIDColumn,
		TickerID:            TickerIDColumn,
		Quantity:            QuantityColumn,
		TradeOrderID:        TradeOrderIDColumn,
		CreatedAt:           CreatedAtColumn,
		RebalancerRunID:     RebalancerRunIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
