//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var InterestRate = newInterestRateTable("public", "interest_rate", "")

type interestRateTable struct {
	postgres.Table

	//Columns
	InterestRateID postgres.ColumnString
	Date           postgres.ColumnDate
	DurationMonths postgres.ColumnInteger
	InterestRate   postgres.ColumnFloat

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type InterestRateTable struct {
	interestRateTable

	EXCLUDED interestRateTable
}

// AS creates new InterestRateTable with assigned alias
func (a InterestRateTable) AS(alias string) *InterestRateTable {
	return newInterestRateTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InterestRateTable with assigned schema name
func (a InterestRateTable) FromSchema(schemaName string) *InterestRateTable {
	return newInterestRateTable(schemaName, a.TableName(), a.Alias())
}

func newInterestRateTable(schemaName, tableName, alias string) *InterestRateTable {
	return &InterestRateTable{
		interestRateTable: newInterestRateTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newInterestRateTableImpl("", "excluded", ""),
	}
}

func newInterestRateTableImpl(schemaName, tableName, alias string) interestRateTable {
	var (
		InterestRateIDColumn = postgres.StringColumn("interest_rate_id")
		DateColumn           = postgres.DateColumn("date")
		DurationMonthsColumn = postgres.IntegerColumn("duration_months")
		InterestRateColumn   = postgres.FloatColumn("interest_rate")
		allColumns           = postgres.ColumnList{InterestRateIDColumn, DateColumn, DurationMonthsColumn, InterestRateColumn}
		mutableColumns       = postgres.ColumnList{DateColumn, DurationMonthsColumn, InterestRateColumn}
	)

	return interestRateTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		InterestRateID: InterestRateIDColumn,
		Date:           DateColumn,
		DurationMonths: DurationMonthsColumn,
		InterestRate:   InterestRateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
