//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var InvestmentRebalanceError = newInvestmentRebalanceErrorTable("public", "investment_rebalance_error", "")

type investmentRebalanceErrorTable struct {
	postgres.Table

	//Columns
	InvestmentRebalanceErrorID postgres.ColumnString
	RebalancerRunID            postgres.ColumnString
	InvestmentID               postgres.ColumnString
	ErrorMessage               postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type InvestmentRebalanceErrorTable struct {
	investmentRebalanceErrorTable

	EXCLUDED investmentRebalanceErrorTable
}

// AS creates new InvestmentRebalanceErrorTable with assigned alias
func (a InvestmentRebalanceErrorTable) AS(alias string) *InvestmentRebalanceErrorTable {
	return newInvestmentRebalanceErrorTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InvestmentRebalanceErrorTable with assigned schema name
func (a InvestmentRebalanceErrorTable) FromSchema(schemaName string) *InvestmentRebalanceErrorTable {
	return newInvestmentRebalanceErrorTable(schemaName, a.TableName(), a.Alias())
}

func newInvestmentRebalanceErrorTable(schemaName, tableName, alias string) *InvestmentRebalanceErrorTable {
	return &InvestmentRebalanceErrorTable{
		investmentRebalanceErrorTable: newInvestmentRebalanceErrorTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newInvestmentRebalanceErrorTableImpl("", "excluded", ""),
	}
}

func newInvestmentRebalanceErrorTableImpl(schemaName, tableName, alias string) investmentRebalanceErrorTable {
	var (
		InvestmentRebalanceErrorIDColumn = postgres.StringColumn("investment_rebalance_error_id")
		RebalancerRunIDColumn            = postgres.StringColumn("rebalancer_run_id")
		InvestmentIDColumn               = postgres.StringColumn("investment_id")
		ErrorMessageColumn               = postgres.StringColumn("error_message")
		allColumns                       = postgres.ColumnList{InvestmentRebalanceErrorIDColumn, RebalancerRunIDColumn, InvestmentIDColumn, ErrorMessageColumn}
		mutableColumns                   = postgres.ColumnList{RebalancerRunIDColumn, InvestmentIDColumn, ErrorMessageColumn}
	)

	return investmentRebalanceErrorTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		InvestmentRebalanceErrorID: InvestmentRebalanceErrorIDColumn,
		RebalancerRunID:            RebalancerRunIDColumn,
		InvestmentID:               InvestmentIDColumn,
		ErrorMessage:               ErrorMessageColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
