//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var InvestmentHoldingsVersion = newInvestmentHoldingsVersionTable("public", "investment_holdings_version", "")

type investmentHoldingsVersionTable struct {
	postgres.Table

	//Columns
	InvestmentHoldingsVersionID postgres.ColumnString
	InvestmentID                postgres.ColumnString
	CreatedAt                   postgres.ColumnTimestampz
	RebalancerRunID             postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type InvestmentHoldingsVersionTable struct {
	investmentHoldingsVersionTable

	EXCLUDED investmentHoldingsVersionTable
}

// AS creates new InvestmentHoldingsVersionTable with assigned alias
func (a InvestmentHoldingsVersionTable) AS(alias string) *InvestmentHoldingsVersionTable {
	return newInvestmentHoldingsVersionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InvestmentHoldingsVersionTable with assigned schema name
func (a InvestmentHoldingsVersionTable) FromSchema(schemaName string) *InvestmentHoldingsVersionTable {
	return newInvestmentHoldingsVersionTable(schemaName, a.TableName(), a.Alias())
}

func newInvestmentHoldingsVersionTable(schemaName, tableName, alias string) *InvestmentHoldingsVersionTable {
	return &InvestmentHoldingsVersionTable{
		investmentHoldingsVersionTable: newInvestmentHoldingsVersionTableImpl(schemaName, tableName, alias),
		EXCLUDED:                       newInvestmentHoldingsVersionTableImpl("", "excluded", ""),
	}
}

func newInvestmentHoldingsVersionTableImpl(schemaName, tableName, alias string) investmentHoldingsVersionTable {
	var (
		InvestmentHoldingsVersionIDColumn = postgres.StringColumn("investment_holdings_version_id")
		InvestmentIDColumn                = postgres.StringColumn("investment_id")
		CreatedAtColumn                   = postgres.TimestampzColumn("created_at")
		RebalancerRunIDColumn             = postgres.StringColumn("rebalancer_run_id")
		allColumns                        = postgres.ColumnList{InvestmentHoldingsVersionIDColumn, InvestmentIDColumn, CreatedAtColumn, RebalancerRunIDColumn}
		mutableColumns                    = postgres.ColumnList{InvestmentIDColumn, CreatedAtColumn, RebalancerRunIDColumn}
	)

	return investmentHoldingsVersionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		InvestmentHoldingsVersionID: InvestmentHoldingsVersionIDColumn,
		InvestmentID:                InvestmentIDColumn,
		CreatedAt:                   CreatedAtColumn,
		RebalancerRunID:             RebalancerRunIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
