//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var InvestmentHoldings = newInvestmentHoldingsTable("public", "investment_holdings", "")

type investmentHoldingsTable struct {
	postgres.Table

	//Columns
	HoldingsID           postgres.ColumnString
	StrategyInvestmentID postgres.ColumnString
	Date                 postgres.ColumnDate
	Ticker               postgres.ColumnString
	Quantity             postgres.ColumnFloat
	CreatedAt            postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type InvestmentHoldingsTable struct {
	investmentHoldingsTable

	EXCLUDED investmentHoldingsTable
}

// AS creates new InvestmentHoldingsTable with assigned alias
func (a InvestmentHoldingsTable) AS(alias string) *InvestmentHoldingsTable {
	return newInvestmentHoldingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InvestmentHoldingsTable with assigned schema name
func (a InvestmentHoldingsTable) FromSchema(schemaName string) *InvestmentHoldingsTable {
	return newInvestmentHoldingsTable(schemaName, a.TableName(), a.Alias())
}

func newInvestmentHoldingsTable(schemaName, tableName, alias string) *InvestmentHoldingsTable {
	return &InvestmentHoldingsTable{
		investmentHoldingsTable: newInvestmentHoldingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newInvestmentHoldingsTableImpl("", "excluded", ""),
	}
}

func newInvestmentHoldingsTableImpl(schemaName, tableName, alias string) investmentHoldingsTable {
	var (
		HoldingsIDColumn           = postgres.StringColumn("holdings_id")
		StrategyInvestmentIDColumn = postgres.StringColumn("strategy_investment_id")
		DateColumn                 = postgres.DateColumn("date")
		TickerColumn               = postgres.StringColumn("ticker")
		QuantityColumn             = postgres.FloatColumn("quantity")
		CreatedAtColumn            = postgres.TimestampzColumn("created_at")
		allColumns                 = postgres.ColumnList{HoldingsIDColumn, StrategyInvestmentIDColumn, DateColumn, TickerColumn, QuantityColumn, CreatedAtColumn}
		mutableColumns             = postgres.ColumnList{StrategyInvestmentIDColumn, DateColumn, TickerColumn, QuantityColumn, CreatedAtColumn}
	)

	return investmentHoldingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		HoldingsID:           HoldingsIDColumn,
		StrategyInvestmentID: StrategyInvestmentIDColumn,
		Date:                 DateColumn,
		Ticker:               TickerColumn,
		Quantity:             QuantityColumn,
		CreatedAt:            CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
