//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ReconciliationRun = newReconciliationRunTable("public", "reconciliation_run", "")

type reconciliationRunTable struct {
	postgres.Table

	// Columns
	ReconciliationRunID postgres.ColumnString
	Status              postgres.ColumnString
	BrokerSnapshot      postgres.ColumnString
	LedgerSnapshot      postgres.ColumnString
	ProposedAdjustments postgres.ColumnString
	AppliedAt           postgres.ColumnTimestampz
	CreatedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ReconciliationRunTable struct {
	reconciliationRunTable

	EXCLUDED reconciliationRunTable
}

// AS creates new ReconciliationRunTable with assigned alias
func (a ReconciliationRunTable) AS(alias string) *ReconciliationRunTable {
	return newReconciliationRunTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReconciliationRunTable with assigned schema name
func (a ReconciliationRunTable) FromSchema(schemaName string) *ReconciliationRunTable {
	return newReconciliationRunTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReconciliationRunTable with assigned table prefix
func (a ReconciliationRunTable) WithPrefix(prefix string) *ReconciliationRunTable {
	return newReconciliationRunTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReconciliationRunTable with assigned table suffix
func (a ReconciliationRunTable) WithSuffix(suffix string) *ReconciliationRunTable {
	return newReconciliationRunTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReconciliationRunTable(schemaName, tableName, alias string) *ReconciliationRunTable {
	return &ReconciliationRunTable{
		reconciliationRunTable: newReconciliationRunTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newReconciliationRunTableImpl("", "excluded", ""),
	}
}

func newReconciliationRunTableImpl(schemaName, tableName, alias string) reconciliationRunTable {
	var (
		ReconciliationRunIDColumn = postgres.StringColumn("reconciliation_run_id")
		StatusColumn              = postgres.StringColumn("status")
		BrokerSnapshotColumn      = postgres.StringColumn("broker_snapshot")
		LedgerSnapshotColumn      = postgres.StringColumn("ledger_snapshot")
		ProposedAdjustmentsColumn = postgres.StringColumn("proposed_adjustments")
		AppliedAtColumn           = postgres.TimestampzColumn("applied_at")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		allColumns                = postgres.ColumnList{ReconciliationRunIDColumn, StatusColumn, BrokerSnapshotColumn, LedgerSnapshotColumn, ProposedAdjustmentsColumn, AppliedAtColumn, CreatedAtColumn}
		mutableColumns            = postgres.ColumnList{StatusColumn, BrokerSnapshotColumn, LedgerSnapshotColumn, ProposedAdjustmentsColumn, AppliedAtColumn, CreatedAtColumn}
	)

	return reconciliationRunTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ReconciliationRunID: ReconciliationRunIDColumn,
		Status:              StatusColumn,
		BrokerSnapshot:      BrokerSnapshotColumn,
		LedgerSnapshot:      LedgerSnapshotColumn,
		ProposedAdjustments: ProposedAdjustmentsColumn,
		AppliedAt:           AppliedAtColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
