//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AdjustedPrice = AdjustedPrice.FromSchema(schema)
	APIRequest = APIRequest.FromSchema(schema)
	AppUserProfile = AppUserProfile.FromSchema(schema)
	AssetFundamental = AssetFundamental.FromSchema(schema)
	AssetUniverse = AssetUniverse.FromSchema(schema)
	AssetUniverseTicker = AssetUniverseTicker.FromSchema(schema)
	ContactMessage = ContactMessage.FromSchema(schema)
	EmailPreference = EmailPreference.FromSchema(schema)
	ExcessTradeVolume = ExcessTradeVolume.FromSchema(schema)
	FactorScore = FactorScore.FromSchema(schema)
	InterestRate = InterestRate.FromSchema(schema)
	Investment = Investment.FromSchema(schema)
	InvestmentHoldings = InvestmentHoldings.FromSchema(schema)
	InvestmentHoldingsVersion = InvestmentHoldingsVersion.FromSchema(schema)
	InvestmentRebalance = InvestmentRebalance.FromSchema(schema)
	InvestmentRebalanceError = InvestmentRebalanceError.FromSchema(schema)
	InvestmentTrade = InvestmentTrade.FromSchema(schema)
	LatencyTracking = LatencyTracking.FromSchema(schema)
	RebalancePrice = RebalancePrice.FromSchema(schema)
	RebalancerRun = RebalancerRun.FromSchema(schema)
	SchemaVersion = SchemaVersion.FromSchema(schema)
	Strategy = Strategy.FromSchema(schema)
	StrategyRun = StrategyRun.FromSchema(schema)
	Ticker = Ticker.FromSchema(schema)
	TradeOrder = TradeOrder.FromSchema(schema)
	UserAccount = UserAccount.FromSchema(schema)
	UserStrategy = UserStrategy.FromSchema(schema)
}
