//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserAccount = newUserAccountTable("public", "user_account", "")

type userAccountTable struct {
	postgres.Table

	// Columns
	UserAccountID postgres.ColumnString
	FirstName     postgres.ColumnString
	LastName      postgres.ColumnString
	Email         postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz
	PhoneNumber   postgres.ColumnString
	Provider      postgres.ColumnString
	ProviderID    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserAccountTable struct {
	userAccountTable

	EXCLUDED userAccountTable
}

// AS creates new UserAccountTable with assigned alias
func (a UserAccountTable) AS(alias string) *UserAccountTable {
	return newUserAccountTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserAccountTable with assigned schema name
func (a UserAccountTable) FromSchema(schemaName string) *UserAccountTable {
	return newUserAccountTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserAccountTable with assigned table prefix
func (a UserAccountTable) WithPrefix(prefix string) *UserAccountTable {
	return newUserAccountTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserAccountTable with assigned table suffix
func (a UserAccountTable) WithSuffix(suffix string) *UserAccountTable {
	return newUserAccountTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserAccountTable(schemaName, tableName, alias string) *UserAccountTable {
	return &UserAccountTable{
		userAccountTable: newUserAccountTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newUserAccountTableImpl("", "excluded", ""),
	}
}

func newUserAccountTableImpl(schemaName, tableName, alias string) userAccountTable {
	var (
		UserAccountIDColumn = postgres.StringColumn("user_account_id")
		FirstNameColumn     = postgres.StringColumn("first_name")
		LastNameColumn      = postgres.StringColumn("last_name")
		EmailColumn         = postgres.StringColumn("email")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		PhoneNumberColumn   = postgres.StringColumn("phone_number")
		ProviderColumn      = postgres.StringColumn("provider")
		ProviderIDColumn    = postgres.StringColumn("provider_id")
		allColumns          = postgres.ColumnList{UserAccountIDColumn, FirstNameColumn, LastNameColumn, EmailColumn, CreatedAtColumn, UpdatedAtColumn, PhoneNumberColumn, ProviderColumn, ProviderIDColumn}
		mutableColumns      = postgres.ColumnList{FirstNameColumn, LastNameColumn, EmailColumn, CreatedAtColumn, UpdatedAtColumn, PhoneNumberColumn, ProviderColumn, ProviderIDColumn}
	)

	return userAccountTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserAccountID: UserAccountIDColumn,
		FirstName:     FirstNameColumn,
		LastName:      LastNameColumn,
		Email:         EmailColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,
		PhoneNumber:   PhoneNumberColumn,
		Provider:      ProviderColumn,
		ProviderID:    ProviderIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
