//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmailOtp = newEmailOtpTable("app_auth", "email_otp", "")

type emailOtpTable struct {
	postgres.Table

	// Columns
	EmailOtpID    postgres.ColumnString
	Email         postgres.ColumnString
	CodeHash      postgres.ColumnString
	ExpiresAt     postgres.ColumnTimestampz
	AttemptsLeft  postgres.ColumnInteger
	ConsumedAt    postgres.ColumnTimestampz
	IPCreatedFrom postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type EmailOtpTable struct {
	emailOtpTable

	EXCLUDED emailOtpTable
}

// AS creates new EmailOtpTable with assigned alias
func (a EmailOtpTable) AS(alias string) *EmailOtpTable {
	return newEmailOtpTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmailOtpTable with assigned schema name
func (a EmailOtpTable) FromSchema(schemaName string) *EmailOtpTable {
	return newEmailOtpTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmailOtpTable with assigned table prefix
func (a EmailOtpTable) WithPrefix(prefix string) *EmailOtpTable {
	return newEmailOtpTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmailOtpTable with assigned table suffix
func (a EmailOtpTable) WithSuffix(suffix string) *EmailOtpTable {
	return newEmailOtpTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmailOtpTable(schemaName, tableName, alias string) *EmailOtpTable {
	return &EmailOtpTable{
		emailOtpTable: newEmailOtpTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newEmailOtpTableImpl("", "excluded", ""),
	}
}

func newEmailOtpTableImpl(schemaName, tableName, alias string) emailOtpTable {
	var (
		EmailOtpIDColumn    = postgres.StringColumn("email_otp_id")
		EmailColumn         = postgres.StringColumn("email")
		CodeHashColumn      = postgres.StringColumn("code_hash")
		ExpiresAtColumn     = postgres.TimestampzColumn("expires_at")
		AttemptsLeftColumn  = postgres.IntegerColumn("attempts_left")
		ConsumedAtColumn    = postgres.TimestampzColumn("consumed_at")
		IPCreatedFromColumn = postgres.StringColumn("ip_created_from")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{EmailOtpIDColumn, EmailColumn, CodeHashColumn, ExpiresAtColumn, AttemptsLeftColumn, ConsumedAtColumn, IPCreatedFromColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{EmailColumn, CodeHashColumn, ExpiresAtColumn, AttemptsLeftColumn, ConsumedAtColumn, IPCreatedFromColumn, CreatedAtColumn}
	)

	return emailOtpTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		EmailOtpID:    EmailOtpIDColumn,
		Email:         EmailColumn,
		CodeHash:      CodeHashColumn,
		ExpiresAt:     ExpiresAtColumn,
		AttemptsLeft:  AttemptsLeftColumn,
		ConsumedAt:    ConsumedAtColumn,
		IPCreatedFrom: IPCreatedFromColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
