//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserSession = newUserSessionTable("app_auth", "user_session", "")

type userSessionTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	UserAccountID postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz
	ExpiresAt     postgres.ColumnTimestampz
	LastSeenAt    postgres.ColumnTimestampz
	IP            postgres.ColumnString
	UserAgent     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserSessionTable struct {
	userSessionTable

	EXCLUDED userSessionTable
}

// AS creates new UserSessionTable with assigned alias
func (a UserSessionTable) AS(alias string) *UserSessionTable {
	return newUserSessionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserSessionTable with assigned schema name
func (a UserSessionTable) FromSchema(schemaName string) *UserSessionTable {
	return newUserSessionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserSessionTable with assigned table prefix
func (a UserSessionTable) WithPrefix(prefix string) *UserSessionTable {
	return newUserSessionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserSessionTable with assigned table suffix
func (a UserSessionTable) WithSuffix(suffix string) *UserSessionTable {
	return newUserSessionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserSessionTable(schemaName, tableName, alias string) *UserSessionTable {
	return &UserSessionTable{
		userSessionTable: newUserSessionTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newUserSessionTableImpl("", "excluded", ""),
	}
}

func newUserSessionTableImpl(schemaName, tableName, alias string) userSessionTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		UserAccountIDColumn = postgres.StringColumn("user_account_id")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		ExpiresAtColumn     = postgres.TimestampzColumn("expires_at")
		LastSeenAtColumn    = postgres.TimestampzColumn("last_seen_at")
		IPColumn            = postgres.StringColumn("ip")
		UserAgentColumn     = postgres.StringColumn("user_agent")
		allColumns          = postgres.ColumnList{IDColumn, UserAccountIDColumn, CreatedAtColumn, ExpiresAtColumn, LastSeenAtColumn, IPColumn, UserAgentColumn}
		mutableColumns      = postgres.ColumnList{UserAccountIDColumn, CreatedAtColumn, ExpiresAtColumn, LastSeenAtColumn, IPColumn, UserAgentColumn}
	)

	return userSessionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		UserAccountID: UserAccountIDColumn,
		CreatedAt:     CreatedAtColumn,
		ExpiresAt:     ExpiresAtColumn,
		LastSeenAt:    LastSeenAtColumn,
		IP:            IPColumn,
		UserAgent:     UserAgentColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
