version: '3.7'
services:
    postgres:
        image: postgres:14-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres_test
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5440:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    app:
      container_name: factorbacktest_api
      build:
        context: ./
        dockerfile: ./Dockerfile
      ports:
        - 3009:3009
      depends_on:
        - postgres
      environment:
          - ALPHA_ENV=test