version: '3.7'
services:
    postgres:
        container_name: factorbacktest_db
        image: postgres:14-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5440:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
    # app:
    #   container_name: factorbacktest_api
    #   build:
    #     context: ./
    #     dockerfile: ./Dockerfile
    #   ports:
    #     - 3009:3009
    #   depends_on:
    #     - postgres
    #   environment:
    #       - ALPHA_ENV=test

    # test:
    #   container_name: factorbacktest_test
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   environment:
    #     POSTGRES_DB: postgres_test
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: postgres
    #     ALPHA_ENV: test
    #     IS_DOCKER: "true"
    #   depends_on:
    #     - app
    #     - postgres
    #   command: go test -v ./...