apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-backend
  template:
    metadata:
      labels:
        app: alpha-backend
    spec:
      containers:
      - name: alpha-backend-container
        image: 326651360928.dkr.ecr.us-east-1.amazonaws.com/factorbacktest:latest
        imagePullPolicy: Always # Set this to Always or IfNotPresent
        ports:
        - containerPort: 3009
        volumeMounts:
          - name: secrets-volume
            mountPath: /secrets.json
      volumes:
      - name: secrets-volume
        secret:
          secretName: alpha-secrets  # kubectl create secret generic alpha-secrets --from-file=secrets.json
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-backend-service
spec:
  selector:
    app: alpha-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3009
  type: LoadBalancer
