// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/price.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/data/price.service.go -destination=internal/data/mocks/mock_price.service.go
//

// Package mock_data is a generated GoMock package.
package mock_data

import (
	context "context"
	sql "database/sql"
	data "factorbacktest/internal/data"
	repository "factorbacktest/internal/repository"
	reflect "reflect"
	time "time"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockPriceService is a mock of PriceService interface.
type MockPriceService struct {
	ctrl     *gomock.Controller
	recorder *MockPriceServiceMockRecorder
}

// MockPriceServiceMockRecorder is the mock recorder for MockPriceService.
type MockPriceServiceMockRecorder struct {
	mock *MockPriceService
}

// NewMockPriceService creates a new mock instance.
func NewMockPriceService(ctrl *gomock.Controller) *MockPriceService {
	mock := &MockPriceService{ctrl: ctrl}
	mock.recorder = &MockPriceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceService) EXPECT() *MockPriceServiceMockRecorder {
	return m.recorder
}

// GetLatestPrices mocks base method.
func (m *MockPriceService) GetLatestPrices(ctx context.Context, symbols []string) (map[string]decimal.Decimal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestPrices", ctx, symbols)
	ret0, _ := ret[0].(map[string]decimal.Decimal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPrices indicates an expected call of GetLatestPrices.
func (mr *MockPriceServiceMockRecorder) GetLatestPrices(ctx, symbols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPrices", reflect.TypeOf((*MockPriceService)(nil).GetLatestPrices), ctx, symbols)
}

// IngestPrices mocks base method.
func (m *MockPriceService) IngestPrices(ctx context.Context, tx *sql.Tx, symbol string, adjPricesRepository repository.AdjustedPriceRepository, start *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestPrices", ctx, tx, symbol, adjPricesRepository, start)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestPrices indicates an expected call of IngestPrices.
func (mr *MockPriceServiceMockRecorder) IngestPrices(ctx, tx, symbol, adjPricesRepository, start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestPrices", reflect.TypeOf((*MockPriceService)(nil).IngestPrices), ctx, tx, symbol, adjPricesRepository, start)
}

// LoadPriceCache mocks base method.
func (m *MockPriceService) LoadPriceCache(ctx context.Context, inputs []data.LoadPriceCacheInput, stdevs []data.LoadStdevCacheInput) (*data.PriceCache, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPriceCache", ctx, inputs, stdevs)
	ret0, _ := ret[0].(*data.PriceCache)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPriceCache indicates an expected call of LoadPriceCache.
func (mr *MockPriceServiceMockRecorder) LoadPriceCache(ctx, inputs, stdevs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPriceCache", reflect.TypeOf((*MockPriceService)(nil).LoadPriceCache), ctx, inputs, stdevs)
}

// UpdateUniversePrices mocks base method.
func (m *MockPriceService) UpdateUniversePrices(ctx context.Context, tx *sql.Tx, tickerRepository repository.TickerRepository, adjPricesRepository repository.AdjustedPriceRepository) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUniversePrices", ctx, tx, tickerRepository, adjPricesRepository)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUniversePrices indicates an expected call of UpdateUniversePrices.
func (mr *MockPriceServiceMockRecorder) UpdateUniversePrices(ctx, tx, tickerRepository, adjPricesRepository any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUniversePrices", reflect.TypeOf((*MockPriceService)(nil).UpdateUniversePrices), ctx, tx, tickerRepository, adjPricesRepository)
}
