// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/strategy.repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/strategy.repository.go -destination=internal/repository/mocks/mock_strategy.repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "factorbacktest/internal/db/models/postgres/public/model"
	repository "factorbacktest/internal/repository"
	reflect "reflect"

	postgres "github.com/go-jet/jet/v2/postgres"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStrategyRepository is a mock of StrategyRepository interface.
type MockStrategyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyRepositoryMockRecorder
}

// MockStrategyRepositoryMockRecorder is the mock recorder for MockStrategyRepository.
type MockStrategyRepositoryMockRecorder struct {
	mock *MockStrategyRepository
}

// NewMockStrategyRepository creates a new mock instance.
func NewMockStrategyRepository(ctrl *gomock.Controller) *MockStrategyRepository {
	mock := &MockStrategyRepository{ctrl: ctrl}
	mock.recorder = &MockStrategyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategyRepository) EXPECT() *MockStrategyRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m_2 *MockStrategyRepository) Add(m model.Strategy) (*model.Strategy, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Add", m)
	ret0, _ := ret[0].(*model.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockStrategyRepositoryMockRecorder) Add(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStrategyRepository)(nil).Add), m)
}

// AddRun mocks base method.
func (m *MockStrategyRepository) AddRun(arg0 model.StrategyRun) (*model.StrategyRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRun", arg0)
	ret0, _ := ret[0].(*model.StrategyRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRun indicates an expected call of AddRun.
func (mr *MockStrategyRepositoryMockRecorder) AddRun(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRun", reflect.TypeOf((*MockStrategyRepository)(nil).AddRun), arg0)
}

// Get mocks base method.
func (m *MockStrategyRepository) Get(arg0 uuid.UUID) (*model.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*model.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStrategyRepositoryMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStrategyRepository)(nil).Get), arg0)
}

// GetIfBookmarked mocks base method.
func (m *MockStrategyRepository) GetIfBookmarked(arg0 model.Strategy) (*model.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIfBookmarked", arg0)
	ret0, _ := ret[0].(*model.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIfBookmarked indicates an expected call of GetIfBookmarked.
func (mr *MockStrategyRepositoryMockRecorder) GetIfBookmarked(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIfBookmarked", reflect.TypeOf((*MockStrategyRepository)(nil).GetIfBookmarked), arg0)
}

// GetLatestPublishedRun mocks base method.
func (m *MockStrategyRepository) GetLatestPublishedRun(strategyID uuid.UUID) (*model.StrategyRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestPublishedRun", strategyID)
	ret0, _ := ret[0].(*model.StrategyRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPublishedRun indicates an expected call of GetLatestPublishedRun.
func (mr *MockStrategyRepositoryMockRecorder) GetLatestPublishedRun(strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPublishedRun", reflect.TypeOf((*MockStrategyRepository)(nil).GetLatestPublishedRun), strategyID)
}

// List mocks base method.
func (m *MockStrategyRepository) List(arg0 repository.StrategyListFilter) ([]model.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]model.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStrategyRepositoryMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStrategyRepository)(nil).List), arg0)
}

// Update mocks base method.
func (m *MockStrategyRepository) Update(arg0 model.Strategy, arg1 postgres.ColumnList) (*model.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*model.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStrategyRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStrategyRepository)(nil).Update), arg0, arg1)
}
