// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/email_otp.repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/email_otp.repository.go -destination=internal/repository/mocks/mock_email_otp.repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "factorbacktest/internal/db/models/postgres/app_auth/model"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailOTPRepository is a mock of EmailOTPRepository interface.
type MockEmailOTPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailOTPRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailOTPRepositoryMockRecorder is the mock recorder for MockEmailOTPRepository.
type MockEmailOTPRepositoryMockRecorder struct {
	mock *MockEmailOTPRepository
}

// NewMockEmailOTPRepository creates a new mock instance.
func NewMockEmailOTPRepository(ctrl *gomock.Controller) *MockEmailOTPRepository {
	mock := &MockEmailOTPRepository{ctrl: ctrl}
	mock.recorder = &MockEmailOTPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailOTPRepository) EXPECT() *MockEmailOTPRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailOTPRepository) Create(ctx context.Context, in *model.EmailOtp) (*model.EmailOtp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*model.EmailOtp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEmailOTPRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailOTPRepository)(nil).Create), ctx, in)
}

// DecrementAttempts mocks base method.
func (m *MockEmailOTPRepository) DecrementAttempts(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementAttempts", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementAttempts indicates an expected call of DecrementAttempts.
func (mr *MockEmailOTPRepositoryMockRecorder) DecrementAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementAttempts", reflect.TypeOf((*MockEmailOTPRepository)(nil).DecrementAttempts), ctx, id)
}

// LatestUnconsumedByEmail mocks base method.
func (m *MockEmailOTPRepository) LatestUnconsumedByEmail(ctx context.Context, email string, now time.Time) (*model.EmailOtp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestUnconsumedByEmail", ctx, email, now)
	ret0, _ := ret[0].(*model.EmailOtp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestUnconsumedByEmail indicates an expected call of LatestUnconsumedByEmail.
func (mr *MockEmailOTPRepositoryMockRecorder) LatestUnconsumedByEmail(ctx, email, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestUnconsumedByEmail", reflect.TypeOf((*MockEmailOTPRepository)(nil).LatestUnconsumedByEmail), ctx, email, now)
}

// MarkConsumed mocks base method.
func (m *MockEmailOTPRepository) MarkConsumed(ctx context.Context, id uuid.UUID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConsumed", ctx, id, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConsumed indicates an expected call of MarkConsumed.
func (mr *MockEmailOTPRepositoryMockRecorder) MarkConsumed(ctx, id, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConsumed", reflect.TypeOf((*MockEmailOTPRepository)(nil).MarkConsumed), ctx, id, now)
}
