// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/ses_email.repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/ses_email.repository.go -destination=internal/repository/mocks/mock_ses_email.repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailRepository is a mock of EmailRepository interface.
type MockEmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRepositoryMockRecorder
}

// MockEmailRepositoryMockRecorder is the mock recorder for MockEmailRepository.
type MockEmailRepositoryMockRecorder struct {
	mock *MockEmailRepository
}

// NewMockEmailRepository creates a new mock instance.
func NewMockEmailRepository(ctrl *gomock.Controller) *MockEmailRepository {
	mock := &MockEmailRepository{ctrl: ctrl}
	mock.recorder = &MockEmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRepository) EXPECT() *MockEmailRepositoryMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailRepository) SendEmail(to, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", to, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailRepositoryMockRecorder) SendEmail(to, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailRepository)(nil).SendEmail), to, subject, body)
}

// SendEmailWithTemplate mocks base method.
func (m *MockEmailRepository) SendEmailWithTemplate(to, subject, templateName string, templateData any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailWithTemplate", to, subject, templateName, templateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailWithTemplate indicates an expected call of SendEmailWithTemplate.
func (mr *MockEmailRepositoryMockRecorder) SendEmailWithTemplate(to, subject, templateName, templateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailWithTemplate", reflect.TypeOf((*MockEmailRepository)(nil).SendEmailWithTemplate), to, subject, templateName, templateData)
}
