// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/investment_rebalance.repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/investment_rebalance.repository.go -destination=internal/repository/mocks/mock_investment_rebalance.repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	sql "database/sql"
	model "factorbacktest/internal/db/models/postgres/public/model"
	reflect "reflect"

	postgres "github.com/go-jet/jet/v2/postgres"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInvestmentRebalanceRepository is a mock of InvestmentRebalanceRepository interface.
type MockInvestmentRebalanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvestmentRebalanceRepositoryMockRecorder
	isgomock struct{}
}

// MockInvestmentRebalanceRepositoryMockRecorder is the mock recorder for MockInvestmentRebalanceRepository.
type MockInvestmentRebalanceRepositoryMockRecorder struct {
	mock *MockInvestmentRebalanceRepository
}

// NewMockInvestmentRebalanceRepository creates a new mock instance.
func NewMockInvestmentRebalanceRepository(ctrl *gomock.Controller) *MockInvestmentRebalanceRepository {
	mock := &MockInvestmentRebalanceRepository{ctrl: ctrl}
	mock.recorder = &MockInvestmentRebalanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvestmentRebalanceRepository) EXPECT() *MockInvestmentRebalanceRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockInvestmentRebalanceRepository) Add(tx *sql.Tx, ir model.InvestmentRebalance) (*model.InvestmentRebalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", tx, ir)
	ret0, _ := ret[0].(*model.InvestmentRebalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockInvestmentRebalanceRepositoryMockRecorder) Add(tx, ir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockInvestmentRebalanceRepository)(nil).Add), tx, ir)
}

// Get mocks base method.
func (m *MockInvestmentRebalanceRepository) Get(tx *sql.Tx, id uuid.UUID) (*model.InvestmentRebalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tx, id)
	ret0, _ := ret[0].(*model.InvestmentRebalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInvestmentRebalanceRepositoryMockRecorder) Get(tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInvestmentRebalanceRepository)(nil).Get), tx, id)
}

// HasPendingForInvestment mocks base method.
func (m *MockInvestmentRebalanceRepository) HasPendingForInvestment(investmentID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPendingForInvestment", investmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPendingForInvestment indicates an expected call of HasPendingForInvestment.
func (mr *MockInvestmentRebalanceRepositoryMockRecorder) HasPendingForInvestment(investmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPendingForInvestment", reflect.TypeOf((*MockInvestmentRebalanceRepository)(nil).HasPendingForInvestment), investmentID)
}

// List mocks base method.
func (m *MockInvestmentRebalanceRepository) List(tx *sql.Tx) ([]model.InvestmentRebalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tx)
	ret0, _ := ret[0].([]model.InvestmentRebalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInvestmentRebalanceRepositoryMockRecorder) List(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInvestmentRebalanceRepository)(nil).List), tx)
}

// ListByRebalancerRunID mocks base method.
func (m *MockInvestmentRebalanceRepository) ListByRebalancerRunID(tx *sql.Tx, rebalancerRunID uuid.UUID) ([]model.InvestmentRebalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRebalancerRunID", tx, rebalancerRunID)
	ret0, _ := ret[0].([]model.InvestmentRebalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRebalancerRunID indicates an expected call of ListByRebalancerRunID.
func (mr *MockInvestmentRebalanceRepositoryMockRecorder) ListByRebalancerRunID(tx, rebalancerRunID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRebalancerRunID", reflect.TypeOf((*MockInvestmentRebalanceRepository)(nil).ListByRebalancerRunID), tx, rebalancerRunID)
}

// Update mocks base method.
func (m *MockInvestmentRebalanceRepository) Update(tx *sql.Tx, ir model.InvestmentRebalance, columns postgres.ColumnList) (*model.InvestmentRebalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tx, ir, columns)
	ret0, _ := ret[0].(*model.InvestmentRebalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInvestmentRebalanceRepositoryMockRecorder) Update(tx, ir, columns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvestmentRebalanceRepository)(nil).Update), tx, ir, columns)
}
