//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type EmailOtp struct {
	EmailOtpID    uuid.UUID `sql:"primary_key"`
	Email         string
	CodeHash      string
	ExpiresAt     time.Time
	AttemptsLeft  int32
	ConsumedAt    *time.Time
	IPCreatedFrom *string
	CreatedAt     time.Time
}
