//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserSession struct {
	ID            string `sql:"primary_key"`
	UserAccountID uuid.UUID
	CreatedAt     time.Time
	ExpiresAt     time.Time
	LastSeenAt    time.Time
	IP            *string
	UserAgent     *string
}
