create type asset_fundamental_granularity as enum('QUARTERLY', 'ANNUAL');

CREATE TABLE asset_fundamental(
  id serial primary key,
  symbol text not null,
  granularity asset_fundamental_granularity not null,
  start_date date not null,
  end_date date not null,
  created_at timestamp with time zone,
  revenue decimal,
  cost_of_revenue decimal,
  gross_profit decimal,
  operating_income decimal,
  total_assets decimal,
  total_current_assets decimal,
  prepaid_expenses decimal,
  property_plant_and_equipment_net decimal,
  retained_earnings decimal,
  other_assets_noncurrent decimal,
  total_non_current_assets decimal,
  total_liabilities decimal,
  shareholder_equity decimal,
  net_income decimal,
  shares_outstanding_diluted decimal,
  shares_outstanding_basic decimal,
  eps_diluted decimal,
  eps_basic decimal,
  operating_cash_flow decimal,
  investing_cash_flow decimal,
  financing_cash_flow decimal,
  net_cash_flow decimal,
  research_development_expense decimal,
  selling_general_administrative_expense decimal,
  operating_expenses decimal,
  non_operating_income decimal,
  pre_tax_income decimal,
  income_tax decimal,
  depreciation_amortization decimal,
  stock_based_compensation decimal,
  dividends_paid decimal,
  cash_on_hand decimal,
  current_net_receivables decimal,
  inventory decimal,
  total_current_liabilities decimal,
  total_non_current_liabilities decimal,
  long_term_debt decimal,
  total_long_term_liabilities decimal,
  goodwill decimal,
  intangible_assets_excluding_goodwill decimal
);