// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/strategy_summary.app.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/strategy_summary.app.go -destination=internal/app/mocks/mock_strategy_summary.app.go
//

// Package mock_app is a generated GoMock package.
package mock_app

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategySummaryApp is a mock of StrategySummaryApp interface.
type MockStrategySummaryApp struct {
	ctrl     *gomock.Controller
	recorder *MockStrategySummaryAppMockRecorder
}

// MockStrategySummaryAppMockRecorder is the mock recorder for MockStrategySummaryApp.
type MockStrategySummaryAppMockRecorder struct {
	mock *MockStrategySummaryApp
}

// NewMockStrategySummaryApp creates a new mock instance.
func NewMockStrategySummaryApp(ctrl *gomock.Controller) *MockStrategySummaryApp {
	mock := &MockStrategySummaryApp{ctrl: ctrl}
	mock.recorder = &MockStrategySummaryAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategySummaryApp) EXPECT() *MockStrategySummaryAppMockRecorder {
	return m.recorder
}

// SendSavedStrategySummaryEmails mocks base method.
func (m *MockStrategySummaryApp) SendSavedStrategySummaryEmails(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSavedStrategySummaryEmails", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSavedStrategySummaryEmails indicates an expected call of SendSavedStrategySummaryEmails.
func (mr *MockStrategySummaryAppMockRecorder) SendSavedStrategySummaryEmails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSavedStrategySummaryEmails", reflect.TypeOf((*MockStrategySummaryApp)(nil).SendSavedStrategySummaryEmails), ctx)
}
