// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/email.service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/email.service.go -destination=internal/service/mocks/mock_email.service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "factorbacktest/internal/db/models/postgres/public/model"
	domain "factorbacktest/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// GenerateStrategySummaryEmail mocks base method.
func (m *MockEmailService) GenerateStrategySummaryEmail(user *model.UserAccount, strategyResults []domain.StrategySummaryResult) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateStrategySummaryEmail", user, strategyResults)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateStrategySummaryEmail indicates an expected call of GenerateStrategySummaryEmail.
func (mr *MockEmailServiceMockRecorder) GenerateStrategySummaryEmail(user, strategyResults any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateStrategySummaryEmail", reflect.TypeOf((*MockEmailService)(nil).GenerateStrategySummaryEmail), user, strategyResults)
}

// SendStrategySummaryEmail mocks base method.
func (m *MockEmailService) SendStrategySummaryEmail(user *model.UserAccount, strategyResults []domain.StrategySummaryResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendStrategySummaryEmail", user, strategyResults)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendStrategySummaryEmail indicates an expected call of SendStrategySummaryEmail.
func (mr *MockEmailServiceMockRecorder) SendStrategySummaryEmail(user, strategyResults any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendStrategySummaryEmail", reflect.TypeOf((*MockEmailService)(nil).SendStrategySummaryEmail), user, strategyResults)
}
