//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type AdjustedPrice struct {
	ID        int32 `sql:"primary_key"`
	Date      time.Time
	Symbol    string
	Price     decimal.Decimal
	CreatedAt time.Time
}
