//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type APIRequestLatency struct {
	RequestID         *uuid.UUID
	Route             *string
	StartTs           *time.Time
	TotalProcessingMs *int64
	ProcessingTimes   *string
	Version           *string
}
