//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AssetFundamental struct {
	AfID                                uuid.UUID `sql:"primary_key"`
	Symbol                              string
	StartDate                           time.Time
	EndDate                             time.Time
	CreatedAt                           *time.Time
	Revenue                             *float64
	CostOfRevenue                       *float64
	GrossProfit                         *float64
	OperatingIncome                     *float64
	TotalAssets                         *float64
	TotalCurrentAssets                  *float64
	PrepaidExpenses                     *float64
	PropertyPlantAndEquipmentNet        *float64
	RetainedEarnings                    *float64
	OtherAssetsNoncurrent               *float64
	TotalNonCurrentAssets               *float64
	TotalLiabilities                    *float64
	ShareholderEquity                   *float64
	NetIncome                           *float64
	SharesOutstandingDiluted            *float64
	SharesOutstandingBasic              *float64
	EpsDiluted                          *float64
	EpsBasic                            *float64
	OperatingCashFlow                   *float64
	InvestingCashFlow                   *float64
	FinancingCashFlow                   *float64
	NetCashFlow                         *float64
	ResearchDevelopmentExpense          *float64
	SellingGeneralAdministrativeExpense *float64
	OperatingExpenses                   *float64
	NonOperatingIncome                  *float64
	PreTaxIncome                        *float64
	IncomeTax                           *float64
	DepreciationAmortization            *float64
	StockBasedCompensation              *float64
	DividendsPaid                       *float64
	CashOnHand                          *float64
	CurrentNetReceivables               *float64
	Inventory                           *float64
	TotalCurrentLiabilities             *float64
	TotalNonCurrentLiabilities          *float64
	LongTermDebt                        *float64
	TotalLongTermLiabilities            *float64
	Goodwill                            *float64
	IntangibleAssetsExcludingGoodwill   *float64
}
