//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BacktestJob struct {
	BacktestJobID    uuid.UUID `sql:"primary_key"`
	StrategyID       uuid.UUID
	Status           string
	CurrentStage     *string
	ProgressPct      int
	Result           string
	ErrorMessage     *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
