//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type EmailType string

const (
	EmailType_SavedStrategySummary EmailType = "SAVED_STRATEGY_SUMMARY"
)

func (e *EmailType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "SAVED_STRATEGY_SUMMARY":
		*e = EmailType_SavedStrategySummary
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for EmailType enum")
	}

	return nil
}

func (e EmailType) String() string {
	return string(e)
}
