//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type EmailFrequency string

const (
	EmailFrequency_Daily   EmailFrequency = "DAILY"
	EmailFrequency_Weekly  EmailFrequency = "WEEKLY"
	EmailFrequency_Monthly EmailFrequency = "MONTHLY"
	EmailFrequency_Off     EmailFrequency = "OFF"
)

func (e *EmailFrequency) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "DAILY":
		*e = EmailFrequency_Daily
	case "WEEKLY":
		*e = EmailFrequency_Weekly
	case "MONTHLY":
		*e = EmailFrequency_Monthly
	case "OFF":
		*e = EmailFrequency_Off
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for EmailFrequency enum")
	}

	return nil
}

func (e EmailFrequency) String() string {
	return string(e)
}
