//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type EmailPreference struct {
	EmailPreferenceID uuid.UUID `sql:"primary_key"`
	UserAccountID     uuid.UUID
	EmailType         EmailType
	Frequency         EmailFrequency
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
