//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type FactorScore struct {
	FactorScoreID        uuid.UUID `sql:"primary_key"`
	TickerID             uuid.UUID
	FactorExpressionHash string
	Date                 time.Time
	Score                float64
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
