//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type InvestmentRebalanceError struct {
	InvestmentRebalanceErrorID uuid.UUID `sql:"primary_key"`
	RebalancerRunID            uuid.UUID
	InvestmentID               uuid.UUID
	ErrorMessage               string
}
