//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"

	"github.com/shopspring/decimal"
)

type InvestmentTradeStatus struct {
	InvestmentTradeID *uuid.UUID
	Side              *TradeOrderSide
	Symbol            *string
	Status            *TradeOrderStatus
	Quantity          *decimal.Decimal
	ExpectedPrice     *decimal.Decimal
	ExpectedAmount    *decimal.Decimal
	FilledPrice       *decimal.Decimal
	FilledAmount      *decimal.Decimal
	FilledAt          *time.Time
	RebalancerRunID   *uuid.UUID
	InvestmentID      *uuid.UUID
	TradeOrderID      *uuid.UUID
	TickerID          *uuid.UUID
}
