//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type InvestmentRebalance struct {
	InvestmentRebalanceID uuid.UUID `sql:"primary_key"`
	RebalancerRunID       uuid.UUID
	StrategyInvestmentID  uuid.UUID
	State                 RebalancerRunState
	CreatedAt             time.Time
	ModifiedAt            time.Time
}
