//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"

	"github.com/shopspring/decimal"
)

type LatestInvestmentHoldings struct {
	InvestmentHoldingsID *uuid.UUID
	InvestmentID         *uuid.UUID
	Ticker               *uuid.UUID
	Quantity             *decimal.Decimal
	CreatedAt            *time.Time
	RebalancerRunID      *uuid.UUID
}
