//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"

	"github.com/shopspring/decimal"
)

type LatestPublishedStrategyHoldings struct {
	PublishedStrategyHoldingsID        *uuid.UUID
	PublishedStrategyID                *uuid.UUID
	TickerID                           *uuid.UUID
	Symbol                             *string
	Quantity                           *decimal.Decimal
	CreatedAt                          *time.Time
	PublishedStrategyHoldingsVersionID *uuid.UUID
}
