//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type LatencyTracking struct {
	LatencyTrackingID uuid.UUID `sql:"primary_key"`
	ProcessingTimes   string
	TotalProcessingMs int64
	RequestID         *uuid.UUID
}
