//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LatestStrategyInvestmentHoldings struct {
	StrategyInvestmentHoldingsID *uuid.UUID
	StrategyInvestmentID         *uuid.UUID
	Date                         *time.Time
	Ticker                       *uuid.UUID
	Quantity                     *float64
	Symbol                       *string
}
