//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type LatencySpanStats struct {
	LatencyTrackingID *uuid.UUID
	RequestID         *uuid.UUID
	Route             *string
	StartTs           *time.Time
	Version           *string
	RequestDurationMs *int64
	SpanPath          *string
	SpanName          *string
	Depth             *int32
	ElapsedMs         *int64
}
