//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PublishedStrategyStats struct {
	PublishedStrategyStatsID uuid.UUID `sql:"primary_key"`
	PublishedStrategyID      uuid.UUID
	OneYearReturn            *float64
	TwoYearReturn            *float64
	FiveYearReturn           *float64
	Diversification          *float64
	SharpeRatio              *float64
	CreatedAt                time.Time
	AnnualizedReturn         *float64
	AnnualizedStdev          *float64
}
