//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"

	"github.com/shopspring/decimal"
)

type RebalancePrice struct {
	RebalancePriceID uuid.UUID `sql:"primary_key"`
	TickerID         uuid.UUID
	Price            decimal.Decimal
	RebalancerRunID  uuid.UUID
	CreatedAt        time.Time
}
