//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type RebalancerRun struct {
	RebalancerRunID         uuid.UUID `sql:"primary_key"`
	Date                    time.Time
	CreatedAt               time.Time
	RebalancerRunType       RebalancerRunType
	RebalancerRunState      RebalancerRunState
	ModifiedAt              time.Time
	NumInvestmentsAttempted int32
}
