//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type RebalancerRunState string

const (
	RebalancerRunState_Completed RebalancerRunState = "COMPLETED"
	RebalancerRunState_Pending   RebalancerRunState = "PENDING"
	RebalancerRunState_Error     RebalancerRunState = "ERROR"
)

func (e *RebalancerRunState) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "COMPLETED":
		*e = RebalancerRunState_Completed
	case "PENDING":
		*e = RebalancerRunState_Pending
	case "ERROR":
		*e = RebalancerRunState_Error
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for RebalancerRunState enum")
	}

	return nil
}

func (e RebalancerRunState) String() string {
	return string(e)
}
