//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ReconciliationRun struct {
	ReconciliationRunID uuid.UUID `sql:"primary_key"`
	Status              string
	BrokerSnapshot      string
	LedgerSnapshot      string
	ProposedAdjustments string
	AppliedAt           *time.Time
	CreatedAt           time.Time
}
