//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type SavedStrategy struct {
	SavedStrategyID uuid.UUID `sql:"primary_key"`
	UserAccountID   uuid.UUID
	StrategyID      uuid.UUID
	CreatedAt       time.Time
	ModifiedAt      time.Time
	DeletedAt       *time.Time
}
