//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Strategy struct {
	StrategyID        uuid.UUID `sql:"primary_key"`
	StrategyName      string
	FactorExpression  string
	RebalanceInterval string
	NumAssets         int32
	AssetUniverse     string
	UserAccountID     uuid.UUID
	CreatedAt         time.Time
	ModifiedAt        time.Time
	Published         bool
}
