//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type StrategyInvestment struct {
	StrategyInvestmentID uuid.UUID `sql:"primary_key"`
	AmountDollars        int32
	StartDate            time.Time
	SavedStragyID        uuid.UUID
	UserAccountID        uuid.UUID
	CreatedAt            time.Time
	ModifiedAt           time.Time
}
