//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type StrategyRun struct {
	StrategyRunID    uuid.UUID `sql:"primary_key"`
	StrategyID       uuid.UUID
	StartDate        time.Time
	EndDate          time.Time
	SharpeRatio      *float64
	AnnualizedReturn *float64
	AnnualuzedStdev  *float64
	CreatedAt        time.Time
}
