//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type StrategyInvestmentHoldings struct {
	StrategyInvestmentHoldingsID uuid.UUID `sql:"primary_key"`
	StrategyInvestmentID         uuid.UUID
	Date                         time.Time
	Ticker                       uuid.UUID
	Quantity                     decimal.Decimal
	CreatedAt                    time.Time
}
