//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"

	"github.com/shopspring/decimal"
)

type TradeOrder struct {
	TradeOrderID      uuid.UUID `sql:"primary_key"`
	ProviderID        uuid.UUID
	TickerID          uuid.UUID
	Side              TradeOrderSide
	RequestedQuantity decimal.Decimal
	Status            TradeOrderStatus
	FilledQuantity    *decimal.Decimal
	FilledPrice       *decimal.Decimal
	CreatedAt         *time.Time
	ModifiedAt        *time.Time
	Notes             *string
}
