//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TradeOrderSide string

const (
	TradeOrderSide_Buy  TradeOrderSide = "BUY"
	TradeOrderSide_Sell TradeOrderSide = "SELL"
)

func (e *TradeOrderSide) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "BUY":
		*e = TradeOrderSide_Buy
	case "SELL":
		*e = TradeOrderSide_Sell
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TradeOrderSide enum")
	}

	return nil
}

func (e TradeOrderSide) String() string {
	return string(e)
}
