//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserAccount struct {
	UserAccountID uuid.UUID `sql:"primary_key"`
	FirstName     string
	LastName      string
	Email         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
