//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserStrategy struct {
	UserStrategyID       uuid.UUID `sql:"primary_key"`
	UserID               *uuid.UUID
	StrategyInput        string
	FactorExpressionHash string
	StrategyInputHash    string
	CreatedAt            time.Time
}
