//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserAccountProviderType string

const (
	UserAccountProviderType_Supabase    UserAccountProviderType = "SUPABASE"
	UserAccountProviderType_Google      UserAccountProviderType = "GOOGLE"
	UserAccountProviderType_Manual      UserAccountProviderType = "MANUAL"
	UserAccountProviderType_BetterAuth  UserAccountProviderType = "BETTER_AUTH"
	UserAccountProviderType_LocalGoogle UserAccountProviderType = "LOCAL_GOOGLE"
	UserAccountProviderType_LocalSms    UserAccountProviderType = "LOCAL_SMS"
	UserAccountProviderType_LocalEmail  UserAccountProviderType = "LOCAL_EMAIL"
)

func (e *UserAccountProviderType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "SUPABASE":
		*e = UserAccountProviderType_Supabase
	case "GOOGLE":
		*e = UserAccountProviderType_Google
	case "MANUAL":
		*e = UserAccountProviderType_Manual
	case "BETTER_AUTH":
		*e = UserAccountProviderType_BetterAuth
	case "LOCAL_GOOGLE":
		*e = UserAccountProviderType_LocalGoogle
	case "LOCAL_SMS":
		*e = UserAccountProviderType_LocalSms
	case "LOCAL_EMAIL":
		*e = UserAccountProviderType_LocalEmail
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserAccountProviderType enum")
	}

	return nil
}

func (e UserAccountProviderType) String() string {
	return string(e)
}
