//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LatencySpanStats = newLatencySpanStatsTable("public", "latency_span_stats", "")

type latencySpanStatsTable struct {
	postgres.Table

	// Columns
	LatencyTrackingID postgres.ColumnString
	RequestID         postgres.ColumnString
	Route             postgres.ColumnString
	StartTs           postgres.ColumnTimestampz
	Version           postgres.ColumnString
	RequestDurationMs postgres.ColumnInteger
	SpanPath          postgres.ColumnString
	SpanName          postgres.ColumnString
	Depth             postgres.ColumnInteger
	ElapsedMs         postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type LatencySpanStatsTable struct {
	latencySpanStatsTable

	EXCLUDED latencySpanStatsTable
}

// AS creates new LatencySpanStatsTable with assigned alias
func (a LatencySpanStatsTable) AS(alias string) *LatencySpanStatsTable {
	return newLatencySpanStatsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LatencySpanStatsTable with assigned schema name
func (a LatencySpanStatsTable) FromSchema(schemaName string) *LatencySpanStatsTable {
	return newLatencySpanStatsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LatencySpanStatsTable with assigned table prefix
func (a LatencySpanStatsTable) WithPrefix(prefix string) *LatencySpanStatsTable {
	return newLatencySpanStatsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LatencySpanStatsTable with assigned table suffix
func (a LatencySpanStatsTable) WithSuffix(suffix string) *LatencySpanStatsTable {
	return newLatencySpanStatsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLatencySpanStatsTable(schemaName, tableName, alias string) *LatencySpanStatsTable {
	return &LatencySpanStatsTable{
		latencySpanStatsTable: newLatencySpanStatsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newLatencySpanStatsTableImpl("", "excluded", ""),
	}
}

func newLatencySpanStatsTableImpl(schemaName, tableName, alias string) latencySpanStatsTable {
	var (
		LatencyTrackingIDColumn = postgres.StringColumn("latency_tracking_id")
		RequestIDColumn         = postgres.StringColumn("request_id")
		RouteColumn             = postgres.StringColumn("route")
		StartTsColumn           = postgres.TimestampzColumn("start_ts")
		VersionColumn           = postgres.StringColumn("version")
		RequestDurationMsColumn = postgres.IntegerColumn("request_duration_ms")
		SpanPathColumn          = postgres.StringColumn("span_path")
		SpanNameColumn          = postgres.StringColumn("span_name")
		DepthColumn             = postgres.IntegerColumn("depth")
		ElapsedMsColumn         = postgres.IntegerColumn("elapsed_ms")
		allColumns              = postgres.ColumnList{LatencyTrackingIDColumn, RequestIDColumn, RouteColumn, StartTsColumn, VersionColumn, RequestDurationMsColumn, SpanPathColumn, SpanNameColumn, DepthColumn, ElapsedMsColumn}
		mutableColumns          = postgres.ColumnList{LatencyTrackingIDColumn, RequestIDColumn, RouteColumn, StartTsColumn, VersionColumn, RequestDurationMsColumn, SpanPathColumn, SpanNameColumn, DepthColumn, ElapsedMsColumn}
	)

	return latencySpanStatsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		LatencyTrackingID: LatencyTrackingIDColumn,
		RequestID:         RequestIDColumn,
		Route:             RouteColumn,
		StartTs:           StartTsColumn,
		Version:           VersionColumn,
		RequestDurationMs: RequestDurationMsColumn,
		SpanPath:          SpanPathColumn,
		SpanName:          SpanNameColumn,
		Depth:             DepthColumn,
		ElapsedMs:         ElapsedMsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
