//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LatestRebalanceHoldings = newLatestRebalanceHoldingsTable("public", "latest_rebalance_holdings", "")

type latestRebalanceHoldingsTable struct {
	postgres.Table

	//Columns
	InvestmentHoldingsID        postgres.ColumnString
	RebalancerRunID             postgres.ColumnString
	TickerID                    postgres.ColumnString
	Symbol                      postgres.ColumnString
	Quantity                    postgres.ColumnFloat
	InvestmentID                postgres.ColumnString
	InvestmentHoldingsVersionID postgres.ColumnString
	CreatedAt                   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type LatestRebalanceHoldingsTable struct {
	latestRebalanceHoldingsTable

	EXCLUDED latestRebalanceHoldingsTable
}

// AS creates new LatestRebalanceHoldingsTable with assigned alias
func (a LatestRebalanceHoldingsTable) AS(alias string) *LatestRebalanceHoldingsTable {
	return newLatestRebalanceHoldingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LatestRebalanceHoldingsTable with assigned schema name
func (a LatestRebalanceHoldingsTable) FromSchema(schemaName string) *LatestRebalanceHoldingsTable {
	return newLatestRebalanceHoldingsTable(schemaName, a.TableName(), a.Alias())
}

func newLatestRebalanceHoldingsTable(schemaName, tableName, alias string) *LatestRebalanceHoldingsTable {
	return &LatestRebalanceHoldingsTable{
		latestRebalanceHoldingsTable: newLatestRebalanceHoldingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newLatestRebalanceHoldingsTableImpl("", "excluded", ""),
	}
}

func newLatestRebalanceHoldingsTableImpl(schemaName, tableName, alias string) latestRebalanceHoldingsTable {
	var (
		InvestmentHoldingsIDColumn        = postgres.StringColumn("investment_holdings_id")
		RebalancerRunIDColumn             = postgres.StringColumn("rebalancer_run_id")
		TickerIDColumn                    = postgres.StringColumn("ticker_id")
		SymbolColumn                      = postgres.StringColumn("symbol")
		QuantityColumn                    = postgres.FloatColumn("quantity")
		InvestmentIDColumn                = postgres.StringColumn("investment_id")
		InvestmentHoldingsVersionIDColumn = postgres.StringColumn("investment_holdings_version_id")
		CreatedAtColumn                   = postgres.TimestampzColumn("created_at")
		allColumns                        = postgres.ColumnList{InvestmentHoldingsIDColumn, RebalancerRunIDColumn, TickerIDColumn, SymbolColumn, QuantityColumn, InvestmentIDColumn, InvestmentHoldingsVersionIDColumn, CreatedAtColumn}
		mutableColumns                    = postgres.ColumnList{InvestmentHoldingsIDColumn, RebalancerRunIDColumn, TickerIDColumn, SymbolColumn, QuantityColumn, InvestmentIDColumn, InvestmentHoldingsVersionIDColumn, CreatedAtColumn}
	)

	return latestRebalanceHoldingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		InvestmentHoldingsID:        InvestmentHoldingsIDColumn,
		RebalancerRunID:             RebalancerRunIDColumn,
		TickerID:                    TickerIDColumn,
		Symbol:                      SymbolColumn,
		Quantity:                    QuantityColumn,
		InvestmentID:                InvestmentIDColumn,
		InvestmentHoldingsVersionID: InvestmentHoldingsVersionIDColumn,
		CreatedAt:                   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
