//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LatestExcessTradeVolume = newLatestExcessTradeVolumeTable("public", "latest_excess_trade_volume", "")

type latestExcessTradeVolumeTable struct {
	postgres.Table

	//Columns
	ExcessTradeVolumeID postgres.ColumnString
	TickerID            postgres.ColumnString
	Symbol              postgres.ColumnString
	Quantity            postgres.ColumnFloat
	RebalancerRunID     postgres.ColumnString
	CreatedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type LatestExcessTradeVolumeTable struct {
	latestExcessTradeVolumeTable

	EXCLUDED latestExcessTradeVolumeTable
}

// AS creates new LatestExcessTradeVolumeTable with assigned alias
func (a LatestExcessTradeVolumeTable) AS(alias string) *LatestExcessTradeVolumeTable {
	return newLatestExcessTradeVolumeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LatestExcessTradeVolumeTable with assigned schema name
func (a LatestExcessTradeVolumeTable) FromSchema(schemaName string) *LatestExcessTradeVolumeTable {
	return newLatestExcessTradeVolumeTable(schemaName, a.TableName(), a.Alias())
}

func newLatestExcessTradeVolumeTable(schemaName, tableName, alias string) *LatestExcessTradeVolumeTable {
	return &LatestExcessTradeVolumeTable{
		latestExcessTradeVolumeTable: newLatestExcessTradeVolumeTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newLatestExcessTradeVolumeTableImpl("", "excluded", ""),
	}
}

func newLatestExcessTradeVolumeTableImpl(schemaName, tableName, alias string) latestExcessTradeVolumeTable {
	var (
		ExcessTradeVolumeIDColumn = postgres.StringColumn("excess_trade_volume_id")
		TickerIDColumn            = postgres.StringColumn("ticker_id")
		SymbolColumn              = postgres.StringColumn("symbol")
		QuantityColumn            = postgres.FloatColumn("quantity")
		RebalancerRunIDColumn     = postgres.StringColumn("rebalancer_run_id")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		allColumns                = postgres.ColumnList{ExcessTradeVolumeIDColumn, TickerIDColumn, SymbolColumn, QuantityColumn, RebalancerRunIDColumn, CreatedAtColumn}
		mutableColumns            = postgres.ColumnList{ExcessTradeVolumeIDColumn, TickerIDColumn, SymbolColumn, QuantityColumn, RebalancerRunIDColumn, CreatedAtColumn}
	)

	return latestExcessTradeVolumeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ExcessTradeVolumeID: ExcessTradeVolumeIDColumn,
		TickerID:            TickerIDColumn,
		Symbol:              SymbolColumn,
		Quantity:            QuantityColumn,
		RebalancerRunID:     RebalancerRunIDColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
