//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

// UseSchema sets a new schema name for all generated view SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	APIRequestLatency = APIRequestLatency.FromSchema(schema)
	AssetUniverseSize = AssetUniverseSize.FromSchema(schema)
	InvestmentTradeStatus = InvestmentTradeStatus.FromSchema(schema)
	LatestExcessTradeVolume = LatestExcessTradeVolume.FromSchema(schema)
	LatestInvestmentHoldings = LatestInvestmentHoldings.FromSchema(schema)
	LatestRebalanceHoldings = LatestRebalanceHoldings.FromSchema(schema)
}
