//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var EmailFrequency = &struct {
	Daily   postgres.StringExpression
	Weekly  postgres.StringExpression
	Monthly postgres.StringExpression
	Off     postgres.StringExpression
}{
	Daily:   postgres.NewEnumValue("DAILY"),
	Weekly:  postgres.NewEnumValue("WEEKLY"),
	Monthly: postgres.NewEnumValue("MONTHLY"),
	Off:     postgres.NewEnumValue("OFF"),
}
