//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var RebalancerRunType = &struct {
	ScheduledInvestmentRebalance postgres.StringExpression
	ManualInvestmentRebalance    postgres.StringExpression
	Deposit                      postgres.StringExpression
	Withdrawal                   postgres.StringExpression
}{
	ScheduledInvestmentRebalance: postgres.NewEnumValue("SCHEDULED_INVESTMENT_REBALANCE"),
	ManualInvestmentRebalance:    postgres.NewEnumValue("MANUAL_INVESTMENT_REBALANCE"),
	Deposit:                      postgres.NewEnumValue("DEPOSIT"),
	Withdrawal:                   postgres.NewEnumValue("WITHDRAWAL"),
}
