//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TradeOrderStatus = &struct {
	Pending   postgres.StringExpression
	Completed postgres.StringExpression
	Error     postgres.StringExpression
	Canceled  postgres.StringExpression
}{
	Pending:   postgres.NewEnumValue("PENDING"),
	Completed: postgres.NewEnumValue("COMPLETED"),
	Error:     postgres.NewEnumValue("ERROR"),
	Canceled:  postgres.NewEnumValue("CANCELED"),
}
