package apimodels

// Code generated by tools/generate_api.py. DO NOT EDIT.
// Source: api/openapi.yaml

import (
	"github.com/google/uuid"
)

type BacktestRequest struct {
	FactorOptions struct { Expression string `json:"expression"`; Name string `json:"name"` } `json:"factorOptions"`
	BacktestStart string `json:"backtestStart"`
	BacktestEnd string `json:"backtestEnd"`
	SamplingIntervalUnit string `json:"samplingIntervalUnit"`
	StartCash float64 `json:"startCash"`
	AssetUniverse string `json:"assetUniverse"`
	NumSymbols int `json:"numSymbols"`
	UserID *string `json:"userID"`
}

type BacktestResponse struct {
	FactorName string `json:"factorName"`
	StrategyID uuid.UUID `json:"strategyID"`
	BacktestSnapshots map[string]BacktestSnapshot `json:"backtestSnapshots"`
	LatestHoldings LatestHoldings `json:"latestHoldings"`
	SharpeRatio *float64 `json:"sharpeRatio"`
	AnnualizedReturn *float64 `json:"annualizedReturn"`
	AnnualizedStandardDeviation *float64 `json:"annualizedStandardDeviation"`
}

type BacktestSnapshot struct {
	ValuePercentChange float64 `json:"valuePercentChange"`
	Value float64 `json:"value"`
	Date string `json:"date"`
	AssetMetrics map[string]SnapshotAssetMetrics `json:"assetMetrics"`
}

type SnapshotAssetMetrics struct {
	AssetWeight float64 `json:"assetWeight"`
	FactorScore float64 `json:"factorScore"`
	PriceChangeTilNextResampling *float64 `json:"priceChangeTilNextResampling"`
}

type LatestHoldings struct {
	Date string `json:"date"`
	Assets map[string]SnapshotAssetMetrics `json:"assets"`
}

type BenchmarkRequest struct {
	Symbol string `json:"symbol"`
	Start string `json:"start"`
	End string `json:"end"`
	Granularity string `json:"granularity"`
}

type ContactRequest struct {
	UserID *string `json:"userID"`
	ReplyEmail *string `json:"replyEmail"`
	Content string `json:"content"`
}

type ContactResponse struct {
	Message string `json:"message"`
}

type ConstructFactorEquationRequest struct {
	Input string `json:"input"`
}

type ConstructFactorEquationResponse struct {
	FactorExpression string `json:"factorExpression"`
	Reason string `json:"reason"`
	Error string `json:"error"`
	FactorName string `json:"factorName"`
}

type BacktestBondPortfolioRequest struct {
	BacktestStart string `json:"backtestStart"`
	BacktestEnd string `json:"backtestEnd"`
	DurationKey int `json:"durationKey"`
	StartCash float64 `json:"startCash"`
	UserID *string `json:"userID"`
}

type AddAssetsToUniverseRequest struct {
	UniverseName string `json:"universeName"`
	Assets []interface{} `json:"assets"`
}

type MessageResponse struct {
	Message string `json:"message"`
}

type BookmarkStrategyRequest struct {
	Expression string `json:"expression"`
	Name string `json:"name"`
	RebalanceInterval string `json:"rebalanceInterval"`
	NumAssets int `json:"numAssets"`
	AssetUniverse string `json:"assetUniverse"`
	Bookmark bool `json:"bookmark"`
}

type BookmarkStrategyResponse struct {
	Message string `json:"message"`
	SavedStrategyID uuid.UUID `json:"savedStrategyID"`
}

type IsStrategyBookmarkedResponse struct {
	Name string `json:"name"`
	IsBookmarked bool `json:"isBookmarked"`
}

type GetSavedStrategiesResponse struct {
	StrategyID uuid.UUID `json:"strategyID"`
	StrategyName string `json:"strategyName"`
	RebalanceInterval string `json:"rebalanceInterval"`
	Bookmarked bool `json:"bookmarked"`
	CreatedAt string `json:"createdAt"`
	FactorExpression string `json:"factorExpression"`
	NumAssets int `json:"numAssets"`
	AssetUniverse string `json:"assetUniverse"`
}

type InvestInStrategyRequest struct {
	StrategyID uuid.UUID `json:"strategyID"`
	Amount int `json:"amount"`
}

type InvestInStrategyResponse struct {
	Success bool `json:"success"`
}

type GetInvestmentsResponse struct {
	InvestmentID uuid.UUID `json:"investmentID"`
	OriginalAmountDollars int `json:"originalAmountDollars"`
	StartDate string `json:"startDate"`
	Strategy InvestmentStrategy `json:"strategy"`
	Holdings []Holding `json:"holdings"`
	PercentReturnFraction float64 `json:"percentReturnFraction"`
	CurrentValue float64 `json:"currentValue"`
	CompletedTrades []FilledTrade `json:"completedTrades"`
	Paused bool `json:"paused"`
}

type InvestmentStrategy struct {
	StrategyID uuid.UUID `json:"strategyID"`
	StrategyName string `json:"strategyName"`
	FactorExpression string `json:"factorExpression"`
	NumAssets int `json:"numAssets"`
	AssetUniverse string `json:"assetUniverse"`
	RebalanceInterval string `json:"rebalanceInterval"`
}

type Holding struct {
	Symbol string `json:"symbol"`
	Quantity float64 `json:"quantity"`
	MarketValue float64 `json:"marketValue"`
}

type FilledTrade struct {
	Symbol string `json:"symbol"`
	Quantity float64 `json:"quantity"`
	FillPrice float64 `json:"fillPrice"`
	FilledAt string `json:"filledAt"`
}

type GetPublishedStrategiesResponse struct {
	StrategyID uuid.UUID `json:"strategyID"`
	StrategyName string `json:"strategyName"`
	RebalanceInterval string `json:"rebalanceInterval"`
	CreatedAt string `json:"createdAt"`
	FactorExpression string `json:"factorExpression"`
	NumAssets int `json:"numAssets"`
	AssetUniverse string `json:"assetUniverse"`
	SharpeRatio *float64 `json:"sharpeRatio"`
	AnnualizedReturn *float64 `json:"annualizedReturn"`
	AnnualizedStandardDeviation *float64 `json:"annualizedStandardDeviation"`
	Description *string `json:"description"`
}

type GetAssetUniversesResponse struct {
	DisplayName string `json:"displayName"`
	Code string `json:"code"`
	NumAssets int `json:"numAssets"`
}

type UpdatePricesResponse struct {
	NumUpdatedAssets int `json:"numUpdatedAssets"`
}

type UpdateOrdersResponse struct {
	Success string `json:"success"`
}

type SendSavedStrategySummaryEmailsResponse struct {
	Message string `json:"message"`
}
